/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 spaceship.glb 
Author: MichaelEGA (https://sketchfab.com/michael.evan.allison)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/victory-class-star-destroyer-mark-ii-5d430c5f549a4954a06f2456aabad00b
Title: Victory Class Star Destroyer Mark II
*/

import React from 'react'
import { useGLTF } from '@react-three/drei';
import spaceShipSrc from '../assets/spaceship.glb'

const Spaceship=(props) =>{
  const { nodes, materials } = useGLTF(spaceShipSrc)
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-1.57, 0, 0]} scale={100}>
          <mesh geometry={nodes.plating07_ISD_lod_mat_004_0.geometry} material={materials.ISD_lod_mat_004} />
          <mesh geometry={nodes.plating07_ISD_lod_mat_003_0.geometry} material={materials.ISD_lod_mat_003} />
        </group>
        <mesh geometry={nodes.back_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.bridge_birdge_material01_0.geometry} material={materials.birdge_material01} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.bridgedetail01_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.bridgedetail02_bridge_material03_0.geometry} material={materials.bridge_material03} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.bridgedetail03_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.bridgedetail03_001_hull_material_001_0.geometry} material={materials.hull_material_001} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.cannonmounts_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.ComTower_bridge_material03_0.geometry} material={materials.bridge_material03} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.edgedetail01_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.edgedetail02_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.engine01_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.engine02_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.engine03_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.engine04_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.hangar_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.hangarclamp_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.hull_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.plating01_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.plating02_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.plating03_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.plating04_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.plating05_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.plating06_ISD_lod_mat_002_0.geometry} material={materials.ISD_lod_mat_002} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.plating08_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.plating09_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.plating11_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.ShieldGenL_ISD_Bridge_02_0.geometry} material={materials.ISD_Bridge_02} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.tower_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.towerbase_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.trench_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
        <mesh geometry={nodes.trenchdetail01_hull_material_0.geometry} material={materials.hull_material} rotation={[-1.57, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

export default Spaceship;
